import type { Vocabulary } from "./types";

export const VOCABULARY: Vocabulary[] = [
  // Animals
  { emoji: '🦁', en: 'Lion', vi: 'Sư tử', category: 'animals', phonetic: '/ˈlaɪən/' },
  { emoji: '🐘', en: 'Elephant', vi: 'Con voi', category: 'animals', phonetic: '/ˈelɪfənt/' },
  { emoji: '🦒', en: 'Giraffe', vi: 'Hươu cao cổ', category: 'animals', phonetic: '/dʒəˈrɑːf/' },
  { emoji: '🦓', en: 'Zebra', vi: 'Ngựa vằn', category: 'animals', phonetic: '/ˈziːbrə/' },
  { emoji: '🐢', en: 'Turtle', vi: 'Con rùa', category: 'animals', phonetic: '/ˈtɜːrtl/' },
  { emoji: '🦋', en: 'Butterfly', vi: 'Con bướm', category: 'animals', phonetic: '/ˈbʌtərflaɪ/' },
  { emoji: '🐒', en: 'Monkey', vi: 'Con khỉ', category: 'animals', phonetic: '/ˈmʌŋki/' },
  { emoji: '🐼', en: 'Panda', vi: 'Gấu trúc', category: 'animals', phonetic: '/ˈpændə/' },
  { emoji: '🐨', en: 'Koala', vi: 'Gấu túi', category: 'animals', phonetic: '/koʊˈɑːlə/' },
  { emoji: '🐧', en: 'Penguin', vi: 'Chim cánh cụt', category: 'animals', phonetic: '/ˈpeŋɡwɪn/' },
  { emoji: '🐯', en: 'Tiger', vi: 'Con hổ', category: 'animals', phonetic: '/ˈtaɪɡər/' },
  { emoji: '🦊', en: 'Fox', vi: 'Con cáo', category: 'animals', phonetic: '/fɑːks/' },
  { emoji: '🦉', en: 'Owl', vi: 'Con cú', category: 'animals', phonetic: '/aʊl/' },
  { emoji: '🦈', en: 'Shark', vi: 'Cá mập', category: 'animals', phonetic: '/ʃɑːrk/' },
  { emoji: '🐬', en: 'Dolphin', vi: 'Cá heo', category: 'animals', phonetic: '/ˈdɑːlfɪn/' },
  { emoji: '🐙', en: 'Octopus', vi: 'Bạch tuộc', category: 'animals', phonetic: '/ˈɑːktəpəs/' },
  { emoji: '🦘', en: 'Kangaroo', vi: 'Chuột túi', category: 'animals', phonetic: '/ˌkæŋɡəˈruː/' },
  
  // Fruits
  { emoji: '🍎', en: 'Apple', vi: 'Quả táo', category: 'fruits', phonetic: '/ˈæpl/' },
  { emoji: '🍌', en: 'Banana', vi: 'Quả chuối', category: 'fruits', phonetic: '/bəˈnænə/' },
  { emoji: '🍉', en: 'Watermelon', vi: 'Dưa hấu', category: 'fruits', phonetic: '/ˈwɔːtərmelən/' },
  { emoji: '🍇', en: 'Grapes', vi: 'Quả nho', category: 'fruits', phonetic: '/ɡreɪps/' },
  { emoji: '🍓', en: 'Strawberry', vi: 'Dâu tây', category: 'fruits', phonetic: '/ˈstrɔːberi/' },
  { emoji: '🥝', en: 'Kiwi', vi: 'Quả kiwi', category: 'fruits', phonetic: '/ˈkiːwi/' },
  { emoji: '🍍', en: 'Pineapple', vi: 'Quả dứa', category: 'fruits', phonetic: '/ˈpaɪnæpl/' },
  { emoji: '🍒', en: 'Cherry', vi: 'Quả anh đào', category: 'fruits', phonetic: '/ˈtʃeri/' },
  { emoji: '🍊', en: 'Orange', vi: 'Quả cam', category: 'fruits', phonetic: '/ˈɔːrɪndʒ/' },
  { emoji: '🍋', en: 'Lemon', vi: 'Quả chanh', category: 'fruits', phonetic: '/ˈlemən/' },
  { emoji: '🥭', en: 'Mango', vi: 'Quả xoài', category: 'fruits', phonetic: '/ˈmæŋɡoʊ/' },
  { emoji: '🍈', en: 'Melon', vi: 'Quả dưa', category: 'fruits', phonetic: '/ˈmelən/' },
  { emoji: '🍐', en: 'Pear', vi: 'Quả lê', category: 'fruits', phonetic: '/per/' },
  { emoji: '🥥', en: 'Coconut', vi: 'Quả dừa', category: 'fruits', phonetic: '/ˈkoʊkənʌt/' },
  { emoji: '🫐', en: 'Blueberry', vi: 'Quả việt quất', category: 'fruits', phonetic: '/ˈbluːberi/' },
  { emoji: '🍑', en: 'Peach', vi: 'Quả đào', category: 'fruits', phonetic: '/piːtʃ/' },
  { emoji: '🥑', en: 'Avocado', vi: 'Quả bơ', category: 'fruits', phonetic: '/ˌævəˈkɑːdoʊ/' },
  { emoji: '🍅', en: 'Tomato', vi: 'Quả cà chua', category: 'fruits', phonetic: '/təˈmeɪtoʊ/' },

  // Vehicles
  { emoji: '🚗', en: 'Car', vi: 'Ô tô', category: 'vehicles', phonetic: '/kɑːr/' },
  { emoji: '🚀', en: 'Rocket', vi: 'Tên lửa', category: 'vehicles', phonetic: '/ˈrɑːkɪt/' },
  { emoji: '🚲', en: 'Bicycle', vi: 'Xe đạp', category: 'vehicles', phonetic: '/ˈbaɪsɪkl/' },
  { emoji: '🚁', en: 'Helicopter', vi: 'Trực thăng', category: 'vehicles', phonetic: '/ˈhelɪkɑːptər/' },
  { emoji: '⛵', en: 'Sailboat', vi: 'Thuyền buồm', category: 'vehicles', phonetic: '/ˈseɪlboʊt/' },
  { emoji: '🚂', en: 'Train', vi: 'Tàu hỏa', category: 'vehicles', phonetic: '/treɪn/' },
  { emoji: '🚌', en: 'Bus', vi: 'Xe buýt', category: 'vehicles', phonetic: '/bʌs/' },
  { emoji: '✈️', en: 'Airplane', vi: 'Máy bay', category: 'vehicles', phonetic: '/ˈerpleɪn/' },
  { emoji: '🚑', en: 'Ambulance', vi: 'Xe cứu thương', category: 'vehicles', phonetic: '/ˈæmbjələns/' },
  { emoji: '🚒', en: 'Fire Truck', vi: 'Xe cứu hỏa', category: 'vehicles', phonetic: '/ˈfaɪər trʌk/' },
  { emoji: '🚢', en: 'Ship', vi: 'Tàu thủy', category: 'vehicles', phonetic: '/ʃɪp/' },
  { emoji: '🏍️', en: 'Motorcycle', vi: 'Xe máy', category: 'vehicles', phonetic: '/ˈmoʊtərsaɪkl/' },
  { emoji: '🚜', en: 'Tractor', vi: 'Máy kéo', category: 'vehicles', phonetic: '/ˈtræktər/' },
  { emoji: '🚤', en: 'Speedboat', vi: 'Tàu cao tốc', category: 'vehicles', phonetic: '/ˈspiːdboʊt/' },

  // Weather
  { emoji: '☀️', en: 'Sun', vi: 'Mặt trời', category: 'weather', phonetic: '/sʌn/' },
  { emoji: '☁️', en: 'Cloud', vi: 'Đám mây', category: 'weather', phonetic: '/klaʊd/' },
  { emoji: '🌧️', en: 'Rain', vi: 'Cơn mưa', category: 'weather', phonetic: '/reɪn/' },
  { emoji: '❄️', en: 'Snow', vi: 'Tuyết', category: 'weather', phonetic: '/snoʊ/' },
  { emoji: '🌩️', en: 'Thunder', vi: 'Sấm sét', category: 'weather', phonetic: '/ˈθʌndər/' },
  { emoji: '🌈', en: 'Rainbow', vi: 'Cầu vồng', category: 'weather', phonetic: '/ˈreɪnboʊ/' },
  { emoji: '🌬️', en: 'Wind', vi: 'Gió', category: 'weather', phonetic: '/wɪnd/' },
  { emoji: '🌋', en: 'Volcano', vi: 'Núi lửa', category: 'weather', phonetic: '/vɑːlˈkeɪnoʊ/' },
  { emoji: '🌊', en: 'Wave', vi: 'Sóng biển', category: 'weather', phonetic: '/weɪv/' },
  { emoji: '🌪️', en: 'Tornado', vi: 'Lốc xoáy', category: 'weather', phonetic: '/tɔːrˈneɪdoʊ/' },

  // Sports
  { emoji: '⚽', en: 'Soccer', vi: 'Bóng đá', category: 'sports', phonetic: '/ˈsɑːkər/' },
  { emoji: '🏀', en: 'Basketball', vi: 'Bóng rổ', category: 'sports', phonetic: '/ˈbæskɪtbɔːl/' },
  { emoji: '🎾', en: 'Tennis', vi: 'Quần vợt', category: 'sports', phonetic: '/ˈtenɪs/' },
  { emoji: '🏐', en: 'Volleyball', vi: 'Bóng chuyền', category: 'sports', phonetic: '/ˈvɑːlibɔːl/' },
  { emoji: '🎿', en: 'Skiing', vi: 'Trượt tuyết', category: 'sports', phonetic: '/ˈskiːɪŋ/' },
  { emoji: '🎱', en: 'Billiards', vi: 'Bi-a', category: 'sports', phonetic: '/ˈbɪljərdz/' },
  { emoji: '🎯', en: 'Darts', vi: 'Phi tiêu', category: 'sports', phonetic: '/dɑːrts/' },
  { emoji: '🎳', en: 'Bowling', vi: 'Bowling', category: 'sports', phonetic: '/ˈboʊlɪŋ/' },
  { emoji: '🥊', en: 'Boxing', vi: 'Quyền anh', category: 'sports', phonetic: '/ˈbɑːksɪŋ/' },
  { emoji: '🥋', en: 'Martial Arts', vi: 'Võ thuật', category: 'sports', phonetic: '/ˌmɑːrʃl ˈɑːrts/' },

  // Objects
  { emoji: '🏠', en: 'House', vi: 'Ngôi nhà', category: 'objects', phonetic: '/haʊs/' },
  { emoji: '🎨', en: 'Palette', vi: 'Bảng màu', category: 'objects', phonetic: '/ˈpælət/' },
  { emoji: '🎸', en: 'Guitar', vi: 'Đàn ghi-ta', category: 'objects', phonetic: '/ɡɪˈtɑːr/' },
  { emoji: '📚', en: 'Books', vi: 'Sách', category: 'objects', phonetic: '/bʊks/' },
  { emoji: '🎁', en: 'Gift', vi: 'Quà tặng', category: 'objects', phonetic: '/ɡɪft/' },
  { emoji: '🧸', en: 'Teddy Bear', vi: 'Gấu bông', category: 'objects', phonetic: '/ˈtedi ber/' },
];

export const CATEGORIES = [
  { id: 'all', label: 'Tất cả', icon: '🌟' },
  { id: 'animals', label: 'Động vật', icon: '🦁' },
  { id: 'fruits', label: 'Trái cây', icon: '🍎' },
  { id: 'vehicles', label: 'Phương tiện', icon: '🚀' },
  { id: 'weather', label: 'Thời tiết', icon: '🌈' },
  { id: 'sports', label: 'Thể thao', icon: '⚽' },
  { id: 'objects', label: 'Đồ vật', icon: '🧸' },
];